# This image will be published as dspace/dspace-angular:$DSPACE_VERSION-dist
# See https://github.com/DSpace/dspace-angular/tree/main/docker for usage details
#
# Test build:
# docker build -f Dockerfile.dist -t dspace/dspace-angular:dspace-7_x-dist .

FROM docker.io/node:18-alpine AS build

# Ensure Python and other build tools are available
# These are needed to install some node modules, especially on linux/arm64
RUN apk add --update python3 make g++ && rm -rf /var/cache/apk/*

WORKDIR /app
COPY package.json yarn.lock ./
RUN --mount=type=cache,target=/app/.yarn-cache yarn install --cache-folder .yarn-cache  --frozen-lockfile --network-timeout 300000

ENV NODE_OPTIONS="--max_old_space_size=4096"

ADD . /app/
# Set memory limit for build process - Angular builds require more memory
ENV NODE_OPTIONS="--max_old_space_size=4096"
RUN  --mount=type=cache,target=/app/.angular/cache yarn build:prod

FROM node:18-alpine
ARG CONFIG_YML=config/config.yml
ARG DSPACE_UI_JSON=docker/dspace-ui.json
RUN npm install --global pm2

COPY --chown=node:node --from=build /app/dist /app/dist
COPY --chown=node:node config /app/config
COPY --chown=node:node $DSPACE_UI_JSON /app/dspace-ui.json

WORKDIR /app

COPY $CONFIG_YML /app/config/config.production.yaml
RUN apk add --update net-tools

USER 1000
ENV NODE_ENV=production
EXPOSE 4000
CMD ["pm2-runtime", "start", "dspace-ui.json", "--json"]
